name: validate Factorio Mod

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  validate-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Validate Mod
        uses: xyzzycgn/factorio-mod-uploader-action@2.0.6
        with:
          action: validate
